### ISSUE TITLE
How to trigger a signal?

### ISSUE THREAD

**Issue by approots** [cerebral/redux-action-tree#2]
I've read the documentation, but it's not clear to me how to trigger a signal. The docs here https://github.com/cerebral/redux-action-tree#passing-a-payload-to-a-signal show an event handler (this.props.buttonClicked), but I don't see how that event handler is mapped to a particular signal?

The rest of the docs are quite clear to me and the concept is simple/exciting. Thanks!

**Comment by christianalfoni** [comment]
Hi there :-)

This part in the docs explain that:

To use a signal you connect it just like you connect traditional actions:

``` js
import appMounted from 'signals/appMounted';
...
connect(state => state.app, {appMounted})(App);
```

It would be great if you edited the readme and made that clear in a way you feel fit, I can pull it in :)

**Comment by approots** [comment]
My disconnect is how does `this.props.buttonClicked` trigger the `appMounted` signal? In Redux `mapDispatchToProps` I'd explicitly wire an event handler to an action creator.

**Comment by approots** [comment]
Ahh, `this.props.buttonClicked` is a signal. Perhaps the `connect` example in the docs could include it to make that obvious :-)

```
import appMounted from 'signals/appMounted';
import buttonClicked from 'signals/buttonClicked';
...
connect(state => state.app, {appMounted, buttonClicked})(App);
```

**Comment by christianalfoni** [comment]
Great point! It is fixed, thanks a bunch :)

Let me know if you meet any other lacking documentation or bugs.
