### ISSUE TITLE
async or isAsync?

### ISSUE THREAD

**Issue by volkanunsal** [cerebral/redux-action-tree#4]
Just browsing through the code I found a reference to [`action.isAsync`](https://github.com/cerebral/redux-action-tree/blob/master/src/signal.js#L20). In the README, this property is `async`. So I just wanted to clarify if the documentation is out of date?

**Comment by volkanunsal** [comment]
Sorry, never mind, I just saw this comes from `action-tree` library.

**Comment by Guria** [comment]
We have next imlpementation of the same ideas in function-tree.
Now it is still available in [own repo](https://github.com/cerebral/function-tree) but future updates will be [cerebral monorepo](https://github.com/cerebral/cerebral/tree/master/packages/function-tree).
Also make sure you have read an [article about fuction tree](http://www.christianalfoni.com/articles/2016_09_11_The-case-for-function-tree).

**Comment by volkanunsal** [comment]
@Guria Thanks for these links. I read the article with great interest and read the source code of `function-tree` as well.

I noticed there are a few differences between the implementations. The `output` is handled a little differently in this library than it is in `function-tree`, for example. As in, it's declared in the `context` rather than returned by the function. I think the `function-tree` is much more fully-featured, but this library seems to be easier to get started with on an existing redux app.
